### ISSUE TITLE
how can i

### ISSUE THREAD

**Issue by SLtila** [EdwardVan/Review#1]
how can i config the java
the owner use eclipse or what...
please advice

**Comment by SLtila** [comment]
how can i config the java

**Comment by EdwardVan** [comment]
I suggest that you use IntelliJ idea
It's very good to use
And then direct the project directly to the line
I come from China.
This is what I translated using the translation software

**Comment by SLtila** [comment]
thx a lot buddy

**Comment by SLtila** [comment]
came again and making fun of u
